'use client';

import { useEffect, useState } from 'react';
import { BarChart3, RefreshCw } from 'lucide-react';
import universe from '@/data/fund_universe.json';

type Performance = { oneYear?: number | null; yearToDate?: number | null; threeYear?: number | null };
type Fund = (typeof universe)[number] & { nav?: string; navDate?: string; marketPrice?: number; marketChange?: number; previousClose?: number; purchaseStatus?: string; dailyLimit?: string; premium?: number | null; premiumStatus?: string; performance?: Performance };
type Snapshot = { generatedAt: string | null; funds: Fund[]; sources?: string[]; notes?: string[] };
const initial: Snapshot = { generatedAt: null, funds: universe };
const statusClass: Record<string, string> = { 限大额: 'bg-amber-50 text-amber-700 border-amber-200', 限制大额申购: 'bg-amber-50 text-amber-700 border-amber-200', 暂停申购: 'bg-rose-50 text-rose-700 border-rose-200', 开放申购: 'bg-emerald-50 text-emerald-700 border-emerald-200' };

export default function Home() {
  const [snapshot, setSnapshot] = useState<Snapshot>(initial); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function refresh() {
    setLoading(true); setError('');
    try { const response = await fetch('/api/dashboard', { cache: 'no-store' }); if (!response.ok) throw new Error('实时数据服务暂不可用'); setSnapshot(await response.json()); }
    catch (reason) { setError(reason instanceof Error ? reason.message : '实时数据服务暂不可用'); }
    finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); }, []);
  const etfs = snapshot.funds.filter((fund) => fund.type === '场内ETF').sort((a, b) => (b.premium ?? -Infinity) - (a.premium ?? -Infinity));
  const offMarket = snapshot.funds.filter((fund) => fund.type !== '场内ETF');
  return <main className="min-h-screen bg-[#f4f7f8]">
    <header className="hero-grid border-b border-white/10 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-7 sm:px-8 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#49d0bc] text-[#082d54]"><BarChart3 size={21}/></div><div><p className="text-xs font-semibold tracking-[.18em] text-[#49d0bc]">NASDAQ QDII MONITOR</p><h1 className="font-display text-2xl font-semibold">纳斯达克 QDII 基金看板</h1></div></div><button onClick={() => void refresh()} className="flex shrink-0 items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm text-sky-100 hover:bg-white/15"><RefreshCw size={15} className={loading ? 'animate-spin' : ''}/>{loading ? '更新中' : '刷新数据'}</button></div></header>
    <div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10">
      <div className="mb-8 flex flex-col justify-between gap-3 border-b border-slate-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-sm leading-6 text-slate-600">刷新页面或点击“刷新数据”后，重新获取行情、最新披露净值、申购状态与单日限额。</p><p className="mt-1 text-xs text-slate-400">{snapshot.generatedAt ? `数据请求时间：${new Date(snapshot.generatedAt).toLocaleString('zh-CN', { hour12: false })}` : '正在请求实时数据'}</p></div><p className="text-xs text-slate-400">{snapshot.sources?.join(' · ')}</p></div>
      <section><div><p className="section-kicker">ETF PREMIUM</p><h2 className="section-title">场内纳指 ETF 溢价率排行</h2><p className="mt-2 text-sm text-slate-500">溢价率 =（最新价 - 最新披露单位净值）/ 最新披露单位净值。它反映市价相对最近披露净值的偏离，不是盘中 IOPV 溢价率。</p></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1060px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称 / 代码','昨收','最新价','最新披露单位净值','净值日期','涨跌幅','净值溢价率','近一年收益','今年收益','近3年收益'].map((column) => <th key={column} className="px-5 py-3.5 font-medium">{column}</th>)}</tr></thead><tbody>{etfs.map((fund) => <tr key={fund.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5"><p className="font-medium text-slate-800">{fund.name}</p><p className="mt-.5 font-mono text-xs text-slate-400">{fund.code}</p></td><NumberCell value={fund.previousClose}/><NumberCell value={fund.marketPrice} strong/><td className="px-5 py-3.5 font-mono text-slate-600">{fund.nav ?? '--'}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.navDate ?? '--'}</td><ChangeCell value={fund.marketChange}/><PremiumCell value={fund.premium} title={fund.premiumStatus}/><ReturnCell value={fund.performance?.oneYear}/><ReturnCell value={fund.performance?.yearToDate}/><ReturnCell value={fund.performance?.threeYear}/></tr>)}</tbody></table></div></div></section>
      <section className="mt-14"><div><p className="section-kicker">PURCHASE STATUS & COST</p><h2 className="section-title">场外基金申购状态与费率对比</h2><p className="mt-2 text-sm text-slate-500">申购状态、单日限购额度、最新净值和净值日期来自东方财富/天天基金实时接口；费率为产品合同资料口径。</p></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称','代码','申购状态','单日限购额度','最新净值(元)','净值日期','管理费率','托管费率','综合费率'].map((column) => <th key={column} className="px-5 py-3.5 font-medium">{column}</th>)}</tr></thead><tbody>{offMarket.map((fund) => <tr key={fund.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5 font-medium text-slate-800">{fund.name}</td><td className="px-5 py-3.5 font-mono text-slate-500">{fund.code}</td><td className="px-5 py-3.5"><span className={`status-pill ${statusClass[fund.purchaseStatus ?? ''] ?? 'bg-slate-100 text-slate-600 border-slate-200'}`}>{fund.purchaseStatus ?? '--'}</span></td><td className="px-5 py-3.5 font-mono text-slate-700">{fund.dailyLimit ?? '--'}</td><td className="px-5 py-3.5 font-mono font-medium text-[#0d4a7c]">{fund.nav ?? '--'}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.navDate ?? '--'}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.managementFee}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.custodyFee}</td><td className="px-5 py-3.5 font-mono font-medium text-slate-700">{fund.totalFee}</td></tr>)}</tbody></table></div></div></section>
      {error && <p className="mt-5 text-sm text-rose-700">{error}。请稍后点击刷新重试。</p>}
      <footer className="mt-12 border-t border-slate-200 pt-5 text-xs leading-6 text-slate-400">数据仅供信息参考。基金投资有风险，过往业绩不代表未来表现。</footer>
    </div>
  </main>;
}
function NumberCell({value,strong=false}:{value:number|undefined;strong?:boolean}) { return <td className={`px-5 py-3.5 font-mono ${strong ? 'font-medium text-[#0d4a7c]' : 'text-slate-600'}`}>{value === undefined ? '--' : value.toFixed(3)}</td>; }
function ChangeCell({value}:{value:number|undefined}) { return <td className={`px-5 py-3.5 font-mono font-medium ${value === undefined ? 'text-slate-400' : value >= 0 ? 'text-rose-600' : 'text-emerald-700'}`}>{value === undefined ? '--' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`}</td>; }
function PremiumCell({value,title}:{value:number|null|undefined;title?:string}) { return <td className={`px-5 py-3.5 font-mono font-semibold ${value === undefined || value === null ? 'text-slate-400' : value >= 0 ? 'text-rose-600' : 'text-emerald-700'}`}><span title={title}>{value === undefined || value === null ? '--' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`}</span></td>; }
function ReturnCell({value}:{value:number|undefined|null}) { return <td className={`px-5 py-3.5 font-mono font-medium ${value === undefined || value === null ? 'text-slate-400' : value >= 0 ? 'text-rose-600' : 'text-emerald-700'}`}>{value === undefined || value === null ? '--' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`}</td>; }
