'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, CalendarDays, ChevronDown, CircleDollarSign, Landmark, RefreshCw, Search, TrendingUp } from 'lucide-react';
import universe from '@/data/fund_universe.json';

type Performance = { oneYear?: number | null; yearToDate?: number | null; threeYear?: number | null };
type Fund = (typeof universe)[number] & { nav?: string; navDate?: string; marketPrice?: number; marketChange?: number; previousClose?: number; iopv?: number; purchaseStatus?: string; dailyLimit?: string; premium?: number | null; premiumStatus?: string; performance?: Performance };
type Snapshot = { generatedAt: string | null; funds: Fund[] };
const emptySnapshot: Snapshot = { generatedAt: null, funds: universe };
const statusClass: Record<string, string> = { 限大额: 'bg-amber-50 text-amber-700 border-amber-200', 暂停申购: 'bg-rose-50 text-rose-700 border-rose-200', 开放申购: 'bg-emerald-50 text-emerald-700 border-emerald-200' };

export default function Home() {
  const [type, setType] = useState('全部'); const [query, setQuery] = useState(''); const [all, setAll] = useState(false);
  const [snapshot, setSnapshot] = useState<Snapshot>(emptySnapshot); const [loading, setLoading] = useState(false); const [loadError, setLoadError] = useState(false);
  async function refresh() {
    setLoading(true); setLoadError(false);
    try { const response = await fetch('/api/dashboard', { cache: 'no-store' }); if (!response.ok) throw new Error('live source unavailable'); setSnapshot(await response.json()); }
    catch { setLoadError(true); try { const fallback = await fetch('/data/latest.json', { cache: 'no-store' }); if (fallback.ok) setSnapshot(await fallback.json()); } catch { /* Retain the contractual fund universe. */ } }
    finally { setLoading(false); }
  }
  useEffect(() => { void refresh(); }, []);
  const filtered = snapshot.funds.filter((fund) => (type === '全部' || fund.type === type) && `${fund.name}${fund.code}${fund.type}`.includes(query.trim()));
  const rows = all ? filtered : filtered.slice(0, 10);
  const etfs = snapshot.funds.filter((fund) => fund.type === '场内ETF').sort((a, b) => (b.premium ?? -Infinity) - (a.premium ?? -Infinity));
  const offMarket = snapshot.funds.filter((fund) => fund.type !== '场内ETF');
  const highestPremium = etfs.find((fund) => fund.premium !== null)?.premium;
  return <main>
    <section className="hero-grid border-b border-white/10 text-white"><div className="mx-auto max-w-7xl px-5 pb-10 pt-6 sm:px-8 lg:px-10">
      <nav className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#49d0bc] text-[#082d54]"><BarChart3 size={20}/></div><div><b className="text-sm tracking-[.15em]">INDEX SCOPE</b><p className="text-[10px] tracking-[.22em] text-sky-200">FUND INTELLIGENCE</p></div></div><div className="hidden gap-6 text-sm text-sky-100 md:flex"><a href="#products">产品全景</a><a href="#etf-ranking">ETF 溢价</a><a href="#offmarket">场外申购</a><a href="#insight">策略提示</a></div><button onClick={() => void refresh()} className="flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs text-sky-100 hover:bg-white/15"><RefreshCw size={13} className={loading ? 'animate-spin' : ''}/>{loading ? '更新中' : '刷新数据'}</button></nav>
      <div className="grid gap-8 pt-12 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><p className="mb-4 text-xs font-semibold tracking-[.18em] text-[#49d0bc]">— NASDAQ QDII MONITOR</p><h1 className="font-display text-4xl font-semibold leading-tight sm:text-5xl">纳斯达克 QDII<br/><span className="text-sky-200">基金看板</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-sky-100/80 sm:text-base">将场内 ETF 的实时 IOPV 溢价率、场外申购状态、限额、净值及费率置于一个工作台。刷新页面即可重新请求数据源。</p></div><div className="grid grid-cols-3 gap-3 rounded-2xl border border-white/10 bg-white/[.07] p-4"><Stat value={`${snapshot.funds.length}`} label="纳入产品"/><Stat value={highestPremium === undefined ? '--' : `${highestPremium.toFixed(2)}%`} label="最高 IOPV 溢价" accent="text-[#ffb85c]"/><Stat value={`${offMarket.length}`} label="场外基金" accent="text-[#49d0bc]"/></div></div>
    </div></section>
    <section className="bg-[#f4f7f8] pb-16 pt-6"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-3 md:grid-cols-4"><Metric icon={<TrendingUp size={18}/>} label="场内 ETF" value={`${etfs.length}只`} detail="实时行情与 IOPV" tone="navy"/><Metric icon={<AlertTriangle size={18}/>} label="高溢价预警" value={`${etfs.filter((fund) => (fund.premium ?? 0) > 10).length}只`} detail="IOPV 溢价超过 10%" tone="rose"/><Metric icon={<CircleDollarSign size={18}/>} label="场外可申购" value={`${offMarket.filter((fund) => fund.purchaseStatus === '开放申购').length}只`} detail="以当前接口状态为准" tone="teal"/><Metric icon={<Landmark size={18}/>} label="数据状态" value={loading ? '更新中' : '实时'} detail={snapshot.generatedAt ? new Date(snapshot.generatedAt).toLocaleString('zh-CN', { hour12: false }) : '等待数据'} tone="blue"/></div>
      <div id="products" className="mt-10 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">UNIVERSE</p><h2 className="section-title">产品全景</h2><p className="mt-2 text-sm text-slate-500">合同费率来自基金资料库；行情、净值与申购状态按刷新时实时获取。</p></div><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或代码"/></label></div>
      <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{['全部', '场内ETF', '场外联接', '场外指数', '场外联接(LOF)'].map((value)=><button onClick={()=>setType(value)} key={value} className={`tab-button ${type===value?'tab-button-active':''}`}>{value}</button>)}</div>
      <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称 / 代码','类型','管理费率','托管费率','综合费率','最新市价 / 净值','净值日期','申购状态'].map(x=><th key={x} className="px-5 py-3.5 font-medium">{x}</th>)}</tr></thead><tbody>{rows.map(fund=>{const latest=fund.marketPrice ?? fund.nav; return <tr key={fund.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5"><p className="font-medium text-slate-800">{fund.name}</p><p className="mt-.5 font-mono text-xs text-slate-400">{fund.code}</p></td><td className="px-5 py-3.5"><span className="type-pill">{fund.type}</span></td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.managementFee}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.custodyFee}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.totalFee}</td><td className="px-5 py-3.5 font-mono font-medium text-[#0d4a7c]">{latest ?? '--'}{fund.marketPrice && <span className="ml-1 text-[10px] text-slate-400">市价</span>}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.navDate ?? '--'}</td><td className="px-5 py-3.5"><span className={`status-pill ${statusClass[fund.purchaseStatus ?? ''] ?? 'bg-slate-100 text-slate-600 border-slate-200'}`}>{fund.purchaseStatus ?? '--'}</span></td></tr>})}</tbody></table></div>{filtered.length>10&&<button className="flex w-full items-center justify-center gap-2 border-t border-slate-100 py-3 text-sm font-medium text-[#0d4a7c] hover:bg-sky-50" onClick={()=>setAll(!all)}>{all?'收起列表':`查看全部 ${filtered.length} 只基金`}<ChevronDown className={all?'rotate-180':''} size={16}/></button>}</div>
    </div></section>
    <section id="etf-ranking" className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="section-kicker">LIVE ETF RANKING</p><h2 className="section-title">场内纳指 ETF 溢价率排行</h2><p className="mt-2 text-sm text-slate-500">覆盖 11 只场内 ETF。收益按单位净值累计收益计算，不等同二级市场价格收益。</p></div><p className="text-xs text-slate-400">页面刷新后重新请求行情及 IOPV</p></div><div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称 / 代码','昨收','最新价','IOPV','涨跌幅','溢价率','近一年收益','今年收益','近3年收益'].map(column=><th key={column} className="px-5 py-3.5 font-medium">{column}</th>)}</tr></thead><tbody>{etfs.map(fund=>{const premium=fund.premium; return <tr key={fund.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5"><p className="font-medium text-slate-800">{fund.name}</p><p className="mt-.5 font-mono text-xs text-slate-400">{fund.code}</p></td><NumberCell value={fund.previousClose}/><NumberCell value={fund.marketPrice} strong/><NumberCell value={fund.iopv}/><td className={`px-5 py-3.5 font-mono font-medium ${(fund.marketChange ?? 0) >= 0 ? 'text-rose-600' : 'text-emerald-700'}`}>{fund.marketChange === undefined ? '--' : `${fund.marketChange >= 0 ? '+' : ''}${fund.marketChange.toFixed(2)}%`}</td><td className={`px-5 py-3.5 font-mono font-semibold ${premium === null || premium === undefined ? 'text-slate-400' : premium >= 0 ? 'text-rose-600' : 'text-emerald-700'}`}><span title={fund.premiumStatus}>{premium === null || premium === undefined ? '--' : `${premium >= 0 ? '+' : ''}${premium.toFixed(2)}%`}</span></td><ReturnCell value={fund.performance?.oneYear}/><ReturnCell value={fund.performance?.yearToDate}/><ReturnCell value={fund.performance?.threeYear}/></tr>})}</tbody></table></div><div className="border-t border-slate-100 bg-slate-50 px-5 py-3 text-xs leading-5 text-slate-500">溢价率 =（最新价 - IOPV）/ IOPV。IOPV 缺失或未通过价格合理性校验时显示 “--”，不会使用基金净值替代。收益以各基金最新可得单位净值日为准。</div></div></div></section>
    <section id="offmarket" className="bg-[#eef4f6] py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="section-kicker">PURCHASE STATUS & COST</p><h2 className="section-title">场外基金申购状态与费率对比</h2><p className="mt-2 text-sm text-slate-500">申购状态、单日限额、净值与日期均按刷新时从天天基金接口读取；费率展示产品资料库中的合同口径。</p></div><div className="flex items-center gap-2 text-xs text-slate-400"><CalendarDays size={15}/>动态数据，不写死示例值</div></div><div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称','代码','申购状态','单日限购额度','最新净值(元)','净值日期','管理费率','托管费率','综合费率'].map(column=><th key={column} className="px-5 py-3.5 font-medium">{column}</th>)}</tr></thead><tbody>{offMarket.map(fund=><tr key={fund.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5 font-medium text-slate-800">{fund.name}</td><td className="px-5 py-3.5 font-mono text-slate-500">{fund.code}</td><td className="px-5 py-3.5"><span className={`status-pill ${statusClass[fund.purchaseStatus ?? ''] ?? 'bg-slate-100 text-slate-600 border-slate-200'}`}>{fund.purchaseStatus ?? '--'}</span></td><td className="px-5 py-3.5 font-mono text-slate-700">{fund.dailyLimit ?? '--'}</td><td className="px-5 py-3.5 font-mono font-medium text-[#0d4a7c]">{fund.nav ?? '--'}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.navDate ?? '--'}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.managementFee}</td><td className="px-5 py-3.5 font-mono text-slate-600">{fund.custodyFee}</td><td className="px-5 py-3.5 font-mono font-medium text-slate-700">{fund.totalFee}</td></tr>)}</tbody></table></div></div>{loadError&&<p className="mt-3 text-xs text-amber-700">实时源暂时未响应，当前展示上次可用快照；请稍后刷新复核。</p>}</div></section>
    <section id="insight" className="bg-[#082d54] py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#49d0bc]">DECISION NOTES</p><h2 className="mt-3 font-display text-3xl font-semibold">申购策略与<br/>风险提示</h2><p className="mt-4 text-sm leading-7 text-sky-100/75">场内 ETF 先审视 IOPV 溢价，场外基金先确认限额、开放状态和确认时间。不同通道的核心风险并不相同。</p></div><div className="grid gap-3 sm:grid-cols-2"><Advice n="01" title="辨别交易通道" text="场内 ETF 先审视实时 IOPV 溢价；场外联接先确认限额、开放状态和确认时间。"/><Advice n="02" title="对高溢价保持纪律" text="溢价过高时，价格回归可能直接侵蚀本金。"/><Advice n="03" title="A/C 类按持有期选择" text="长期持有需把申购费与综合费率放在同一口径。"/><Advice n="04" title="关注汇率与估值" text="美元兑人民币、指数估值和 QDII 政策都会改变体验。"/></div></div><p className="mt-10 border-t border-white/15 pt-5 text-xs leading-6 text-sky-100/60">数据源：腾讯财经 ETF 行情、天天基金/东方财富净值与申购状态接口，以及用户提供的基金合同费率资料。基金投资有风险，过往业绩不代表未来表现。</p></div></section>
  </main>;
}
function Stat({value,label,accent='' }:{value:string;label:string;accent?:string}){return <div><p className={`text-2xl font-semibold tabular-nums ${accent}`}>{value}</p><p className="mt-1 text-xs text-sky-100/70">{label}</p></div>}
function Metric({icon,label,value,detail,tone}:{icon:React.ReactNode;label:string;value:string;detail:string;tone:string}){return <article className="metric-card"><div className={`metric-icon metric-${tone}`}>{icon}</div><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 font-display text-xl font-semibold text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div></article>}
function Advice({n,title,text}:{n:string;title:string;text:string}){return <article className="rounded-xl border border-white/10 bg-white/[.06] p-5"><span className="text-xs font-bold tracking-[.16em] text-[#49d0bc]">{n}</span><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-sky-100/70">{text}</p></article>}
function NumberCell({value,strong=false}:{value:number|undefined;strong?:boolean}){return <td className={`px-5 py-3.5 font-mono ${strong ? 'font-medium text-[#0d4a7c]' : 'text-slate-600'}`}>{value === undefined ? '--' : value.toFixed(3)}</td>}
function ReturnCell({value}:{value:number|undefined|null}){const positive=(value??0)>=0;return <td className={`px-5 py-3.5 font-mono font-medium ${value===undefined||value===null?'text-slate-400':positive?'text-rose-600':'text-emerald-700'}`}>{value===undefined||value===null?'--':`${positive?'+':''}${value.toFixed(2)}%`}</td>}
