'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, CalendarDays, ChevronDown, CircleDollarSign, Filter, Landmark, Search, ShieldAlert, TrendingUp } from 'lucide-react';

type Fund = { name: string; code: string; company: string; type: '场内ETF' | '场外联接'; fee: string; premium: number | null; return1y: number; status: string; limit: string };
type LiveFund = { code: string; nav?: string; navDate?: string; marketPrice?: number; purchaseStatus?: string };
type Snapshot = { generatedAt: string | null; funds: LiveFund[] };
const funds: Fund[] = [
  { name: '景顺科技ETF', code: '159509', company: '景顺长城', type: '场内ETF', fee: '1.00%', premium: 23.25, return1y: 33.59, status: '高溢价', limit: '--' },
  { name: '嘉实纳指ETF', code: '159501', company: '嘉实', type: '场内ETF', fee: '0.60%', premium: 11.75, return1y: 19.72, status: '高溢价', limit: '--' },
  { name: '广发纳指ETF', code: '159941', company: '广发', type: '场内ETF', fee: '1.00%', premium: 11.26, return1y: 19.09, status: '高溢价', limit: '--' },
  { name: '国泰纳指ETF', code: '513100', company: '国泰', type: '场内ETF', fee: '0.80%', premium: 10.47, return1y: 15.16, status: '高溢价', limit: '--' },
  { name: '汇添富纳指ETF', code: '159660', company: '汇添富', type: '场内ETF', fee: '0.65%', premium: 10.41, return1y: 19.73, status: '高溢价', limit: '--' },
  { name: '易方达纳指ETF', code: '159696', company: '易方达', type: '场内ETF', fee: '0.60%', premium: 9.34, return1y: 19.87, status: '风险提示', limit: '--' },
  { name: '招商纳指100ETF', code: '159659', company: '招商', type: '场内ETF', fee: '0.65%', premium: 9.05, return1y: 15.68, status: '风险提示', limit: '--' },
  { name: '富国纳指100ETF', code: '513870', company: '富国', type: '场内ETF', fee: '0.60%', premium: 8.61, return1y: 19.77, status: '风险提示', limit: '--' },
  { name: '华安纳指ETF', code: '159632', company: '华安', type: '场内ETF', fee: '0.80%', premium: 8.33, return1y: 19.59, status: '风险提示', limit: '--' },
  { name: '摩根纳指100A', code: '019172', company: '摩根', type: '场外联接', fee: '0.63%', premium: null, return1y: 18.91, status: '限大额', limit: '10元' },
  { name: '易方达纳指联接A', code: '161130', company: '易方达', type: '场外联接', fee: '0.71%', premium: null, return1y: 19.87, status: '限大额', limit: '10元' },
  { name: '华安纳指联接A', code: '040046', company: '华安', type: '场外联接', fee: '1.04%', premium: null, return1y: 19.59, status: '限大额', limit: '10元' },
  { name: '万家纳指100A', code: '019441', company: '万家', type: '场外联接', fee: '0.69%', premium: null, return1y: 18.20, status: '限大额', limit: '10元' },
  { name: '天弘纳指100A', code: '018043', company: '天弘', type: '场外联接', fee: '0.62%', premium: null, return1y: 18.62, status: '限大额', limit: '100元' },
  { name: '博时纳指联接A', code: '016055', company: '博时', type: '场外联接', fee: '0.86%', premium: null, return1y: 19.28, status: '暂停申购', limit: '--' },
];
const statusClass: Record<string, string> = { 高溢价: 'bg-rose-50 text-rose-700 border-rose-200', 风险提示: 'bg-amber-50 text-amber-700 border-amber-200', 限大额: 'bg-blue-50 text-blue-700 border-blue-200', 暂停申购: 'bg-slate-100 text-slate-600 border-slate-200' };

export default function Home() {
  const [type, setType] = useState<'全部' | Fund['type']>('全部'); const [company, setCompany] = useState('全部公司'); const [query, setQuery] = useState(''); const [all, setAll] = useState(false);
  const [snapshot, setSnapshot] = useState<Snapshot>({ generatedAt: null, funds: [] });
  useEffect(() => { fetch('/data/latest.json').then(response => response.ok ? response.json() : null).then(data => data && setSnapshot(data)).catch(() => undefined); }, []);
  const companies = ['全部公司', ...Array.from(new Set(funds.map(x => x.company)))];
  const filtered = funds.filter(x => (type === '全部' || x.type === type) && (company === '全部公司' || x.company === company) && `${x.name}${x.code}${x.company}`.includes(query.trim()));
  const rows = all ? filtered : filtered.slice(0, 10); const premiums = funds.filter(x => x.premium !== null).sort((a,b) => (b.premium ?? 0) - (a.premium ?? 0));
  const liveByCode = new Map(snapshot.funds.map(fund => [fund.code, fund]));
  return <main>
    <section className="hero-grid border-b border-white/10 text-white"><div className="mx-auto max-w-7xl px-5 pb-10 pt-6 sm:px-8 lg:px-10">
      <nav className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#49d0bc] text-[#082d54]"><BarChart3 size={20}/></div><div><b className="text-sm tracking-[.15em]">INDEX SCOPE</b><p className="text-[10px] tracking-[.22em] text-sky-200">FUND INTELLIGENCE</p></div></div><div className="hidden gap-6 text-sm text-sky-100 md:flex"><a href="#products">产品全景</a><a href="#risk">溢价风险</a><a href="#access">申购与费率</a><a href="#insight">策略提示</a></div><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs text-sky-100">数据快照 · 2026.08</span></nav>
      <div className="grid gap-8 pt-12 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><p className="mb-4 text-xs font-semibold tracking-[.18em] text-[#49d0bc]">— NASDAQ QDII MONITOR</p><h1 className="font-display text-4xl font-semibold leading-tight sm:text-5xl">纳斯达克 QDII<br/><span className="text-sky-200">基金看板</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-sky-100/80 sm:text-base">把场内溢价、场外限购、费率结构和业绩表现放在同一个决策工作台。数据来自研究报告快照，仅供横向比较。</p></div><div className="grid grid-cols-3 gap-3 rounded-2xl border border-white/10 bg-white/[.07] p-4"><Stat value="15" label="纳入产品"/><Stat value="23.25%" label="最高溢价" accent="text-[#ffb85c]"/><Stat value="10元" label="主流限额" accent="text-[#49d0bc]"/></div></div>
    </div></section>
    <section className="bg-[#f4f7f8] pb-16 pt-6"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-3 md:grid-cols-4"><Metric icon={<TrendingUp size={18}/>} label="场内 ETF" value="9只" detail="均处于溢价交易状态" tone="navy"/><Metric icon={<AlertTriangle size={18}/>} label="高溢价预警" value="5只" detail="溢价超过 10%" tone="rose"/><Metric icon={<CircleDollarSign size={18}/>} label="场外申购" value="10元" detail="多数产品单日上限" tone="teal"/><Metric icon={<Landmark size={18}/>} label="新增 QDII 额度" value="68.4 亿美元" detail="报告披露的新增额度" tone="blue"/></div>
      <div id="products" className="mt-10 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">UNIVERSE</p><h2 className="section-title">产品全景</h2><p className="mt-2 text-sm text-slate-500">按公司、产品类型或基金名称快速定位。{snapshot.generatedAt ? ` 最新快照：${new Date(snapshot.generatedAt).toLocaleString('zh-CN', { hour12: false })}` : ' 等待最新数据快照。'}</p></div><div className="flex gap-2"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称或代码"/></label><label className="select-box"><Filter size={15}/><select value={company} onChange={e=>setCompany(e.target.value)}>{companies.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label></div></div>
      <div className="mt-5 flex gap-2 overflow-x-auto pb-1">{(['全部','场内ETF','场外联接'] as const).map(x=><button onClick={()=>setType(x)} key={x} className={`tab-button ${type===x?'tab-button-active':''}`}>{x}</button>)}</div>
      <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-[#eaf0f5] text-xs text-slate-500"><tr>{['基金名称 / 代码','基金公司','类型','综合费率','最新市价 / 净值','净值日期','申购状态'].map(x=><th key={x} className="px-5 py-3.5 font-medium">{x}</th>)}</tr></thead><tbody>{rows.map(x=>{const live=liveByCode.get(x.code); const latest=live?.marketPrice ?? live?.nav; return <tr key={x.code} className="border-t border-slate-100 hover:bg-sky-50/50"><td className="px-5 py-3.5"><p className="font-medium text-slate-800">{x.name}</p><p className="mt-.5 font-mono text-xs text-slate-400">{x.code}</p></td><td className="px-5 py-3.5 text-slate-600">{x.company}</td><td className="px-5 py-3.5"><span className="type-pill">{x.type}</span></td><td className="px-5 py-3.5 font-mono text-slate-600">{x.fee}</td><td className="px-5 py-3.5 font-mono font-medium text-[#0d4a7c]">{latest ?? '--'}{live?.marketPrice && <span className="ml-1 text-[10px] text-slate-400">市价</span>}</td><td className="px-5 py-3.5 font-mono text-slate-600">{live?.navDate ?? '--'}</td><td className="px-5 py-3.5"><span className={`status-pill ${statusClass[x.status]}`}>{live?.purchaseStatus ?? x.status}{!live?.purchaseStatus && x.limit !== '--' && ` · ${x.limit}`}</span></td></tr>})}</tbody></table></div>{filtered.length===0&&<p className="p-10 text-center text-sm text-slate-400">没有匹配的基金，请调整筛选条件。</p>}{filtered.length>10&&<button className="flex w-full items-center justify-center gap-2 border-t border-slate-100 py-3 text-sm font-medium text-[#0d4a7c] hover:bg-sky-50" onClick={()=>setAll(!all)}>{all?'收起列表':`查看全部 ${filtered.length} 只基金`}<ChevronDown className={all?'rotate-180':''} size={16}/></button>}</div>
    </div></section>
    <section id="risk" className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-9 px-5 sm:px-8 lg:grid-cols-[.88fr_1.12fr] lg:px-10"><div><p className="section-kicker">PREMIUM WATCH</p><h2 className="section-title">溢价不是收益</h2><p className="mt-4 text-sm leading-7 text-slate-600">场内 ETF 的收盘价与参考净值之间的偏离，可能放大交易价格回归时的损失。当前脚本只展示可靠的最新市价；接入同一时点 IOPV 前，不再把历史净值误算为实时溢价。</p><div className="mt-6 rounded-2xl border border-rose-100 bg-rose-50 p-5"><p className="flex items-center gap-2 font-semibold text-rose-800"><ShieldAlert size={18}/>看板提示</p><p className="mt-2 text-sm leading-6 text-rose-700/85">当溢价超过 10%，应重点复核 IOPV。场外联接基金不适用该指标，应同时关注申购限额与确认节奏。</p></div></div><div className="rounded-2xl border border-slate-200 bg-[#fbfcfd] p-5"><div className="mb-5 flex justify-between"><div><h3 className="font-semibold text-slate-800">场内纳指 ETF 溢价率排行</h3><p className="mt-1 text-xs text-slate-400">研究报告历史快照，非实时指标</p></div><span className="text-xs text-rose-600">红色 = 超过 10%</span></div><div className="space-y-3">{premiums.map(x=><div key={x.code} className="grid grid-cols-[104px_1fr_48px] items-center gap-3 text-xs"><span className="truncate text-slate-600">{x.name}</span><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${x.premium!>=10?'bg-rose-500':'bg-amber-400'}`} style={{width:`${(x.premium!/25)*100}%`}}/></div><span className="font-mono font-medium text-slate-700">{x.premium!.toFixed(2)}%</span></div>)}</div></div></div></section>
    <section id="access" className="bg-[#eef4f6] py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="section-kicker">ACCESS & COST</p><h2 className="section-title">申购门槛与成本结构</h2><div className="mt-8 grid gap-4 lg:grid-cols-3"><Info title="场外申购状态" icon={<CalendarDays size={19}/>} tone="teal" items={['主流产品处于严格限购状态','多数 A/C 类份额：单日 10 元','天弘纳指 100：单日 100 元','博时部分份额：暂停申购']}/><Info title="费率观察" icon={<CircleDollarSign size={19}/>} tone="navy" items={['综合费率区间约 0.63% - 1.38%','摩根纳指 100A：0.63% 低位','C 类通常免申购费，含销售服务费','长期持有需比较 A/C 类费率']}/><Info title="额度与供给" icon={<Landmark size={19}/>} tone="amber" items={['新增 QDII 额度：68.4 亿美元','证券基金类：37.2 亿美元','额度释放有助缓解申购限制','实际开放以基金公司公告为准']}/></div></div></section>
    <section id="insight" className="bg-[#082d54] py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#49d0bc]">DECISION NOTES</p><h2 className="mt-3 font-display text-3xl font-semibold">申购策略与<br/>风险提示</h2><p className="mt-4 text-sm leading-7 text-sky-100/75">把“买哪个”拆成两个问题：你是在支付溢价，还是在接受额度约束？不同渠道的核心风险并不相同。</p></div><div className="grid gap-3 sm:grid-cols-2"><Advice n="01" title="辨别交易通道" text="场内 ETF 先审视实时溢价；场外联接先确认限额、开放状态和确认时间。"/><Advice n="02" title="对高溢价保持纪律" text="溢价超过 10% 时，价格回归会直接侵蚀本金。"/><Advice n="03" title="A/C 类按持有期选择" text="长期持有需把申购费与综合费率放在同一口径。"/><Advice n="04" title="关注汇率与估值" text="美元兑人民币、指数估值和 QDII 政策都会改变体验。"/></div></div><p className="mt-10 border-t border-white/15 pt-5 text-xs leading-6 text-sky-100/60">数据来源：用户提供的纳斯达克 QDII 基金研究报告截图整理。数据为历史快照，可能已不反映当前基金公告、净值、溢价或申购状态。基金投资有风险，过往业绩不代表未来表现。</p></div></section>
  </main>;
}
function Stat({value,label,accent='' }:{value:string;label:string;accent?:string}){return <div><p className={`text-2xl font-semibold tabular-nums ${accent}`}>{value}</p><p className="mt-1 text-xs text-sky-100/70">{label}</p></div>}
function Metric({icon,label,value,detail,tone}:{icon:React.ReactNode;label:string;value:string;detail:string;tone:string}){return <article className="metric-card"><div className={`metric-icon metric-${tone}`}>{icon}</div><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 font-display text-xl font-semibold text-slate-800">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div></article>}
function Info({title,icon,tone,items}:{title:string;icon:React.ReactNode;tone:string;items:string[]}){return <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className={`mb-5 flex h-10 w-10 items-center justify-center rounded-xl icon-${tone}`}>{icon}</div><h3 className="font-semibold text-slate-800">{title}</h3><ul className="mt-4 space-y-3">{items.map(x=><li key={x} className="flex gap-2 text-sm leading-5 text-slate-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-300"/>{x}</li>)}</ul></article>}
function Advice({n,title,text}:{n:string;title:string;text:string}){return <article className="rounded-xl border border-white/10 bg-white/[.06] p-5"><span className="text-xs font-bold tracking-[.16em] text-[#49d0bc]">{n}</span><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-sky-100/70">{text}</p></article>}
